#! /bin/sh

sxhkd &
polybar example &

bspc monitor -d I II III IV V

bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color "#1e90ff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       any

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
